language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="IRMP Arduino Library"
before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
# For the example to run
   - arduino --install-library "TimerOne"
script:
   - build_platform uno
notifications:
  email:
    on_success: always
    on_failure: always
