language: c
sudo: false
cache:
   directories:
   - ~/arduino_ide
   - ~/.arduino15/packages/
git:
   depth: false
   quiet: true
env:
   global:
   - PRETTYNAME="IRMP Arduino Library"
   - INSTALL_PLATFORMS="avr,esp8266,esp32,STM32"
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/ArminJo/travis-ci-arduino/master/install.sh)
#install:
# For the example to run
#- arduino --install-library "TimerOne"
script:
- build_platform BluePill
- build_platform uno
- build_platform esp8266
- build_platform esp32
notifications:
   email:
      recipients:
      - armin.arduino@gmail.com
      on_success: always
      on_failure: always